/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.univr;

import it.univr.bloodModels.BloodModel;
import it.univr.bloodModels.InteractiveBloodModel;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class BloodModelTests {
    private BloodModel bloodModel;

    @Before
    public void initialize() {
        this.bloodModel = new InteractiveBloodModel();
    }

    @Test
    public void testRaisingSugar(){
        int initalSugarLevel = bloodModel.retrieveSugarLevel();
        int amount = 5;
        int iterations = 10;
        int ir = bloodModel.getIncrementRate() + amount;

        bloodModel.addSugar(amount);
        for (int i = 1 ; i <= iterations ; i++){
            assertEquals(initalSugarLevel + ir*i, bloodModel.retrieveSugarLevel());
        }
    }

    @Test
    public void testLoweringSugar(){
        int initalSugarLevel = bloodModel.retrieveSugarLevel();
        int amount = 5;
        int iterations = 10;
        int ir = bloodModel.getIncrementRate() - amount;

        bloodModel.injectInsulin(amount);
        for(int i = 1 ; i <= iterations ; i++){
            assertEquals(initalSugarLevel + i*ir, bloodModel.retrieveSugarLevel());
        }
    }

    @Test
    public void testInvalidValues(){
        int initialIncrementRate = bloodModel.getIncrementRate();
        int amount = -3;
        bloodModel.injectInsulin(amount);
        assertEquals(initialIncrementRate, bloodModel.getIncrementRate());

        bloodModel.addSugar(-3);
        assertEquals(initialIncrementRate, bloodModel.getIncrementRate());
    }
}
