/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.univr;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int sugarLevel = 0;
        int incrementValue = 0;
        int incrementRate = 0;
        int insulinAmount = 30;
        boolean isInteractive = true;
        new AutomatedInsulinPump(sugarLevel, incrementValue, incrementRate, insulinAmount, isInteractive);
    }
}
