/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.univr;

public class App {
    public static void main(String[] args) {
        int sugarLevel = 100;
        int incrementRate = 0;
        int insulinAmount = 30;
        new AutomatedInsulinPump(sugarLevel, incrementRate, insulinAmount, true).run();
    }
}
